[modules]
[modules.preprocessor]
name = "com.scalar.db.benchmarks.ycsb.MultiUserAbacLoader"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.processor]
name = "com.scalar.db.benchmarks.ycsb.MultiUserAbacWorkloadC"
path = "./build/libs/scalardb-benchmarks-all.jar"
[modules.postprocessor]
name = "com.scalar.db.benchmarks.ycsb.YcsbReporter"
path = "./build/libs/scalardb-benchmarks-all.jar"

[common]
concurrency = 2
run_for_sec = 60
ramp_for_sec = 10

[stats]
realtime_report_enabled = true

[ycsb_config]
# マルチユーザーABACモードの設定
user_count = 2           # 並行ユーザー数（スレッド数）
record_count = 1000      # テーブル全体のレコード数
ops_per_tx = 2           # トランザクションあたりの操作数（READ操作）
load_concurrency = 1     # データロード時の並列度
load_batch_size = 10     # バッチサイズ

# ABAC Configuration
abac_enabled = true
abac_attribute_type = "level"
abac_strategy = "random"
abac_attribute_values = "public,confidential,secret"

[database_config]
config_file = "scalardb.properties"
